service: Hana-Report-Automation

provider:
  name: aws
  runtime: python3.11
  stage: staging
  region: ap-southeast-1
  iam:
    role: "${ssm:/HANA_Automation/${sls:stage}/lambda/ROLE}"

package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

functions:
  function:
    handler: handler.main
    description: Report_generator
    events:
      - schedule:
          rate: cron(30 9 ? * TUE-FRI *)
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - ".serverless"

    environment:
      TABLE_NAME_1: "${ssm:/HANA_Automation/${sls:stage}/lambda/TABLE_NAME_1}"
      TABLE_NAME_2: "${ssm:/HANA_Automation/${sls:stage}/lambda/TABLE_NAME_2}"
      BUCKET_NAME: "${ssm:/HANA_Automation/${sls:stage}/lambda/BUCKET_NAME}"
      REGION: "${ssm:/HANA_Automation/${sls:stage}/lambda/REGION}"
      VALUE: "${ssm:/HANA_Automation/${sls:stage}/lambda/ROLE}"
